
spring.datasource.url=jdbc:postgresql://dpg-d17gmm6mcj7s73d6u3qg-a.oregon-postgres.render.com/database_1ydg
spring.datasource.username=database_1ydg_user
spring.datasource.password=zh0C7UeafC5S1k5M0DY9sbIbVavq1PxJ
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=create

#Configuração de exibição de SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
